package com.addressbook.test.utils;

import com.addressbook.app.utils.StringUtils;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class TestStringUtils {

    @Test
    public void testCheckIfInputNotNull() {
        assertFalse(StringUtils.contactInputQuarantine(null));
    }

    @Test
    public void testCheckIfInputNotEmpty() {
        assertFalse(StringUtils.contactInputQuarantine(""));
    }

    @Test
    public void testCheckIfInputNotWhitespace() {
        assertFalse(StringUtils.contactInputQuarantine(" "));
    }

    @Test
    public void testCheckIfPhoneNumberValid() {
        assertAll(
                //! Test cases for valid phone numbers are AI generated by ChatGPT
                //! AI was prompted with "Generate test cases for valid phone numbers"
                //! "I want x format, and to test this regex"
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+1-800-555-5555")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("123-456-7890")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("(123) 456-7890")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+44 20 7946 0958")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+49 30 123456")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("020 7946 0958")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("0800 1111")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+91-9876543210")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("9876543210")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("123.456.7890")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+61 2 1234 5678")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("031-123-4567")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("123-4567")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+33 1 23 45 67 89")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+34 912 34 56 78")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("555-1234")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+1 (800) 123-4567")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("+44 (0) 20 7946 0958")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("0800-123-4567")),
                () -> assertTrue(StringUtils.checkIfPhoneNumber("123 456 7890"))
        );
    }
}