package com.addressbook.app.utils;

public abstract class StringUtils {

    public static boolean checkIfName(String input) {
        return contactInputQuarantine(input);
    }

    public static boolean checkIfPhoneNumber(String input) {
        //? Regular expression for phone number validation
        //? Was originally wrote by me, however to fit different
        //? phone number formats, I had to use a different regex
        //? generated by AI
        String phoneNumberRegex = "^(?!.*--.*)(?!.*\\.-.*)(?!.*-\\..*)(?!.*\\.\\..*)\\+?\\(?\\d[\\d-. ]+\\)?[-. ]?(\\([\\d-. ]+\\))?[\\d-. ]+\\d$";
        return contactInputQuarantine(input) && input.matches(phoneNumberRegex);
    }

    public static boolean checkIfEmail(String input) {
        //? Regular expression for email address validation
        //? Was originally wrote by me, however to fit different
        //? email formats, I had to use a different regex
        //? generated by AI
        String emailRegex = "^(?=[^@]*@[^@]*$)(?!\\.)[A-Za-z0-9+_.-]+(?<!\\.)@((?!\\..*\\.)[A-Za-z0-9][A-Za-z0-9_.-]*[A-Za-z0-9]\\.)+[A-Za-z]{2,6}$";
        return contactInputQuarantine(input) && input.matches(emailRegex);
    }

    public static boolean contactInputQuarantine(String input) {
        if (input == null || input.trim().isEmpty()) {
            throw new IllegalArgumentException("Contact information cannot be null or empty");
        }
        return true;
    }

}
